### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by sortedcord** [nullex86/qtacrylic#1]
Whenever I try to run my program with qtacrylic I get this:

```
qtacrylic.py", line 36, in setAcrylicEffect
    self.SetWindowCompositionAttribute(hWnd, pointer(self.winCompAttrData))
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
```

**Comment by nullex86** [comment]
Hi there, sorry for the late response. I'm guessing you use PyQt instead of
PySide?

If so you have to convert the winId to int first to make it work.

Best regards
- Kevin

**Comment by sortedcord** [comment]
Thanks that fixed it.
